# Set up OpenAI API key.
OPENAI_API_KEY="sk-TiH"
# If you are using the API service provided by OpenAI, include the following line:
OPENAI_API_TYPE="openai"
OPENAI_API_BASE="https://api.feapi.com/v1/"

# If you are using the API service provided by Microsoft Azure, include the following lines:
#OPENAI_API_TYPE="azure"
AZURE_API_BASE="https://api.feapi.com/v1/"
AZURE_API_VERSION="your_azure_api_version"
# Set up You.com search API key.
YDC_API_KEY="bade8f8N2v5f44uLimR8x"

# For Co-STORM
# if use openai encoder
ENCODER_API_TYPE="openai"
# or ENCODER_API_TYPE="azure" if use azure openai encoder

BING_SEARCH_API_KEY = "BING_SEARCH_API_KEY"
SERPER_API_KEY = "your_serper_api_key"
BRAVE_API_KEY = "your_brave_api_key"
TAVILY_API_KEY = "your_tavily_api_key"

